### ISSUE TITLE
features

### ISSUE THREAD

**Issue by m1ckyro5a** [usix79/openquiz#18]
Hello.
Can you add the following features?
1. increasing question length 2 times
2. filling package from json or marked txt
3. customizing question discussion time (for example every fourth question is 40 seconds, and 15 seconds for others) needed for quizbowl packages without buzzer

**Comment by usix79** [comment]
Hi, 
I am planning to publish an update till xmas. Will try to add the features as well.

**Comment by usix79** [comment]
Version 1.19.0 has been published with features you ask.

**Comment by m1ckyro5a** [comment]
Hello.
Can you add something like presentation mode, for fast check representation of questions and answers?

**Comment by usix79** [comment]
Thank you for your continued interest in the product. please open a new issue for this feature. and it would be great if you could tell us a little about how this could work
